import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { TapdConfig } from '../config.ts';

/** 将凭证写入 .env（tapd auth 交互登录成功后） */
export function saveEnvFile(cfg: TapdConfig, cwd = process.cwd()): string {
  const filePath = join(cwd, '.env');
  const content = [
    '# TAPD API credentials (generated by tapd auth)',
    `TAPD_API_USER=${cfg.apiUser}`,
    `TAPD_API_PASSWORD=${cfg.apiPassword}`,
    `TAPD_WORKSPACE_ID=${cfg.workspaceId}`,
    `TAPD_BASE_URL=${cfg.baseURL}`,
    '',
  ].join('\n');
  writeFileSync(filePath, content, 'utf8');
  return filePath;
}
